// Fact patterns shared by the GEO test set (geo-questions.mjs) and the content
// depth model (content-model.mjs): language-independent where the number or
// the name is the fact.
export const F = {
  guests6: /\b6\b|sei |six|sechs|seks|sześ|šest|zes|six|六|6名|6人/i,
  bedrooms3: /\b3\b.{0,25}(camer|bedroom|Schlafzimmer|Zimmer|chambre|soveværelse|soverom|sypialni|ložnic|slaapkamer|卧室|寝室)|(camer|bedroom|Schlafzimmer|chambre|soveværelse|soverom|sypialni|ložnic|slaapkamer).{0,10}\b3\b|三间|3间|3つ|寝室3/i,
  bathrooms2: /\b2\b.{0,25}(bagn|bathroom|Bad|salle|badeværelse|bad|łazien|koupel|badkamer|浴室|卫生间|バスルーム)/i,
  infrared: /infraross|infrasaun|infrared|Infrarot|infrarouge|infrarød|podczerwie|infračerv|infrarood|红外|赤外線/i,
  steam: /bagno turco|steam bath|steam room|Turkish bath|Dampfbad|hammam|dampbad|łaźni[aę] parow|parní lázeň|stoombad|dampbad|蒸汽浴|土耳其浴|スチームバス|ミストサウナ/i,
  privateWellness: /privat|private|privé|prywatn|soukrom|eksklusiv|exclusive|esclusiv|仅供|専用|プライベート|私人/i,
  neverShared: /mai condivis|never shared|nie mit anderen|jamais partag|aldrig delt|aldri delt|nigdy nie|nikdy nesd|nooit gedeeld|不与其他|共有しない|他のゲストと共有/i,
  lifts100: /100\s?(m|metri|meter|metres|mètres|metrů|metrów|米|メートル)/i,
  school50: /50\s?(m|metri|meter|metres|mètres|metrů|metrów|米|メートル)/i,
  centre15: /15[\s-]?(minut|min|Minuten|minutter|minuter|minuten|分)/i,
  address: /Via Saroch/i,
  carosello: /Carosello/i,
  sanRocco: /San Rocco/,
  doss18: /Doss 18/,
  laundry: /lavanderia|launderette|laundromat|Waschsalon|laverie|møntvaskeri|myntvaskeri|pralnia|prádelna|wasserette|自助洗衣|コインランドリー/i,
  supermarkets: /supermercat|supermarket|Supermärkte|supermarché|supermarked|supermarkt|超市|スーパーマーケット/i,
  bus40: /40\s?(m|metri|meter|metres|mètres|metrů|metrów|米|メートル)/i,
  livigno: /Livigno|利维尼奥|リヴィーニョ/i,
  area90: /90\s?(m²|sqm|sq m|square met|平方米|㎡)/i,
  parkingFree: /parcheggio|posto auto|parking|Parkplatz|parkeringsplads|parkeringsplass|parkovac|parkeerplaats|miejsce parkingowe|停车|駐車/i,
  pets: /animali|pets|Haustier|animaux|kæledyr|kjæledyr|zwierz|zvířat|huisdier|宠物|ペット/i,
  breakfast15: /15[,.]?0?0?\s?€|€\s?15|15\s?EUR/i,
  ebike: /e-?bike|E-Bike|vélo électrique|elcykel|el-sykkel|rower elektryczny|elektrokol|elektrische fiets|电动自行车|電動自転車/i,
  ebike35: /35[,.]?0?0?\s?€|€\s?35/i,
  cot: /culla|cot|crib|Babybett|Kinderbett|lit bébé|lit parapluie|tremmeseng|barneseng|łóżeczk|postýlk|kinderbed|婴儿床|ベビーベッド/i,
  highchair: /seggiolone|high chair|Hochstuhl|chaise haute|høj stol|barnestol|krzesełk|židličk|kinderstoel|儿童餐椅|ベビーチェア|ハイチェア/i,
  skiStorage: /deposito (?:per )?sci|ski (?:& bike |and bike )?storage|storage for skis|ski room|Abstellraum für Ski|Ski- und Fahrradabstellraum|opbevaring til ski|rum til ski|berging voor ski|fietsberging|Skiraum|Skiabstell|local à skis|skirum|skibod|przechowalni|lyžárn|skiberging|ski-opslag|滑雪储物|スキー保管|スキー置き場/i,
  whatsapp: /WhatsApp/i,
  phone: /\+39 0342 929285|0342 929285/,
  email: /info@ironwoodlivigno\.com/,
  minStay: /2\s?[-–]\s?3/,
  checkin: /check-?in|Anreise|arrivée|indtjekning|innsjekk|zameldow|příjezd|inchecken|入住|チェックイン/i,
  cancellation: /cancellazion|cancell?ation|Stornierung|annulation|afbestilling|avbestilling|anulow|storno|annulering|取消|キャンセル/i,
  noCommission: /commission|Provision|prowizj|provize|provisie|commissie|佣金|手数料/i,
  fireplace: /camino|fireplace|Kamin|cheminée|pejs|peis|kominek|krb|haard|壁炉|暖炉/i,
  balconies: /balcon|balcony|balconies|Balkon|altan|balkong|balkon|阳台|バルコニー/i,
  wifi: /Wi-?Fi/i,
  hosts: /Francesco/,
  local: /livignasc|born and raised|geboren und aufgewachsen|né et|født og opvokset|født og oppvokst|urodzon|narozen|geboren en getogen|土生土长|生まれ育/i,
  summer: /trekking|hiking|Wander|randonnée|vandre|tur|wędrów|turistik|wandel|徒步|ハイキング/i,
  mtb: /mountain bik|Mountainbike|VTT|mountainbike|rower górski|horské kolo|山地车|マウンテンバイク/i,
  lake: /Lago di Livigno|Lake Livigno|Livigno-?See|lac de Livigno|Livigno-søen|Livignosjøen|jezioro Livigno|jezer[oa] Livigno|meer van Livigno|利维尼奥湖|リヴィーニョ湖/i,
  family: /famigli|famil|Famil|famille|rodzin|rodin|gezin|家庭|家族/i,
  tirano: /Tiran[oau]/,
  milan: /Milano|Milan|Mailand|Mediolan|Milán|Milaan|米兰|ミラノ/i,
  dutyFree: /duty[- ]?free|zollfrei|hors taxes|toldfri|tollfri|bezcł|bezcel|belastingvrij|免税/i,
  mottolino: /Mottolino/,
  season: /novembre|november|Novemb|listopad|maggio|May|Mai|maj|květ|mei|11月|5月/i,
  requestForm: /modulo|form|Formular|formulaire|formular|formulář|formulier|表格|フォーム/i,
  directBooking: /diretta|direct|direkt|bezpośredni|přímo|rechtstreeks|直接/i
};
